name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        clean: false  # Prevents cleaning existing files
        
    - name: Set up Docker permissions
      run: |
        sudo chown -R $USER:$USER $GITHUB_WORKSPACE
        sudo chmod -R 777 $GITHUB_WORKSPACE
    
    - name: Deploy with Docker
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        SOLANA_NETWORK: devnet
        SOLANA_RPC_URL: https://api.devnet.solana.com
        SECRET_KEY: ${{ secrets.PRIVATE_KEY }}
      run: |
        # Navigate to backend directory
        cd backend
        
        # Stop and remove existing containers
        sudo docker-compose down || true
        
        # Remove unused images and clear cache (with error handling)
        sudo docker system prune -af --volumes || true
        
        # Build and start new containers
        sudo docker-compose build --no-cache
        sudo docker-compose up -d
        
        # Verify deployment
        sudo docker ps
        echo "Deployment completed successfully!" 