name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Using self-hosted runner on Ubuntu instance
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy with Docker
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        SOLANA_NETWORK: devnet
        SOLANA_RPC_URL: https://api.devnet.solana.com
        SECRET_KEY: ${{ secrets.PRIVATE_KEY }}
      run: |
        # Navigate to backend directory
        cd backend
        
        # Stop and remove existing containers
        docker-compose down
        
        # Remove unused images and clear cache
        docker system prune -af --volumes
        
        # Build and start new containers
        docker-compose build --no-cache
        docker-compose up -d
        
        # Verify deployment
        docker ps
        echo "Deployment completed successfully!" 